package net.quarxy.twitchBot.utils.permissions;

public enum Permission {
    COMMAND_DUELPOINTS,
    COMMAND_BALANCE,
    COMMAND_ROB,
    COMMAND_PAY,
    COMMAND_MODIFYECONOMY,
    COMMAND_MODIFYDUELPOINTS,
    COMMAND_MODIFY_PERMISSIONS,

    FEATURE_AUTO_TIMEOUT,
    FEATURE_30DAYS_VIP,

    GAME_RUSSIAN_ROULETTE,
    GAME_DUEL
}
